### PR TITLE
More maths features

### PR DESCRIPTION
**Pull request by Artfunkel**
Hi Andy, I've added some more properties to various maths classes. The most important are the three which extract translation, scale, and rotation values from a Matrix4.

I've also merged the scan code patch in.

Want to pull it?

### CODE REVIEW

**Comment by Robmaister** [comment]
Some minor things:
1. Normalizing a matrix isn't normalizing each row individually, it's dividing each element by the determinant. If you still need that kind of functionality, a more proper name might be `RowNormalize()`.
2. `RotationPart` requires a decent amount of calculation and [should probably be a method instead](http://msdn.microsoft.com/en-us/library/ms229054.aspx). Perhaps it's better suited as `Quaternion.CreateFromMatrix`, with a Matrix3 parameter.
3. The `Normalized()`, `Inverted()`, etc. methods are very similar to the existing `Normalize()` and `Invert()` instance methods, which might be a source of confusion/bugs. I can't see any cases where the static methods can't be used instead, but I'm not entirely opposed to the new methods, it's just something to think about.
4. The `ScalePart` property got me thinking that maybe a `Diagonal` property would be nice for all the vectors.
5. You should copy your changes to `Matrix4d` and pull all the relevant changes over to the other matrix classes.

**Comment by Artfunkel** [comment]
Good points. I'll be back online soon to look into implementing them.

**Comment by andykorth** [comment]
Thanks Artfunkel. 

I'm definitely agreed on 1 and 2. 

3) I personally do prefer the convenience of your `<Normalized()>` and Inverted()>`methods. If it was just me, I'd replace (the nonstatic)`<Invert()>`with them... but I'm familiar with the desire for the static Invert methods for those performance reasons. That being said, I don't have any name suggestions, so`<Normalized()>`and`<Inverted()>` is fine with me. 

4) Sure, why not?

5) Yeah, I and others have tried to keep all the Matrix classes in sync, although it's very tiring. I wonder if anyone has any suggests regarding easier solutions or the actual value of having all the matrices have backed by different types. I suspect OpenTK is designed this way because it has some roots in demanding math-heavy scientific simulations?

**Comment by Robmaister** [comment]
3) Yeah, I can see them being used for convenience. And after thinking about it, the only bug that can arise from mixing up the names is calling `mat.Inverted();` in place of `mat.Invert()`, which should be fairly easy to point out. And `Matrix m = mat.Invert();` should result in a compile-time error, so it's really not that bad at all. The method with the least overhead, though, is definitely the static methods with `ref`/`out` parameters.

5) Yeah, they're kept separate because it avoids overhead and makes them very easy to work with in terms of marshaling. There isn't a way to add any sort of inheritance structure to structs outside of interfaces, which introduce a lot of overhead compared to the static `ref`/`out` methods. Our best bet, besides just dealing with tedious work, is to generate the matrix classes from some sort of template. The downside to this is that it would be harder to add and test functionality to the matrix classes.

**Comment by Artfunkel** [comment]
Changes made, except for copying everything into the other classes (I want to make sure we're all happy first).

Thoughts?

**Comment by andykorth** [comment]
Thanks Artfunkel. I will try to take a look tonight.

**Comment by Robmaister** [comment]
Looks good to me.

**Comment by Artfunkel** [comment]
Matrix4, 4d, 3, and 3d are in sync. I'm not sure what's going on with the others though: compare Matrix4x3.CreateTranslation() with Matrix3x4.CreateTranslation(). I think someone with a better understanding of maths ought to take over!

**Comment by andykorth** [comment]
Thanks Artfunkel! The Matrix4x3 and 3x4 aren't really the "main" Matrix classes, so they were never in sync with the others.

**Comment by Robmaister** [comment]
I wrote the Matrix4x3/3x4 classes earlier and included them in one of my pull requests. When I was writing them, I was getting an IQM viewer working in my game and mimicked some of the functionality of the [IQM demo](https://github.com/lsalzman/iqm/tree/master/demo), though the methods may not have strictly done what they were supposed to. I've been meaning to get back to those classes and fix them, been a bit busy, I'll get to that soon. `Matrix3x4.CreateTranslation()` was, in all likelihood, accidentally included when I copied a lot of the functionality over from 4x3 to 3x4.

Also, OpenTK's matrices are column-major, but named as if it were row-major. (If it were really row-major, we'd have to transpose all matrices sent to the GPU) This is fine for square matrices, but when it comes to non-square matrices, there's a discrepancy between the matrix class and it's GLSL equivalent. A Matrix4x3 in GLSL is a mat3x4. There are really 3 solutions to this:
1. Rename rows to columns in all matrix classes and flip class names. This will break the API really badly, probably not a good idea to do this.
2. Swap implementations, this will also break the API, but should be much easier to fix than the first solution.
3. Swap file/class names. This will keep the whole "column-major with row-major naming" thing, but will break the API in a way that is easiest to fix. I'd also have to rename the other non-square matrices like 2x4 to 4x2, 4x2 to 2x4, etc.

**Comment by andykorth** [comment]
> Also, OpenTK's matrices are column-major, but named as if it were row-major. (If it were really row-major, we'd have to transpose all matrices sent to the GPU) 

Yeah, this is a huge pain in my butt. I'd personally be leaning towards number 2, but I think we'd have to talk to the OpenTK community (the forum) before making any changes.

On the plus side, some of the big projects that depend on OpenTk, like monogame, seem to completely ignore all the math classes.

**Pull request merged**
